workflows:
  ionic-ios-workflow:
    name: Ionic iOS Build

    environment:
      node: 18
      xcode: latest

scripts:
  - name: Install dependencies
    script: |
      npm install --legacy-peer-deps
      npm install @angular-devkit/build-angular --save-dev
      npm install -g @ionic/cli

  - name: Build Ionic app
    script: |
      ionic build --prod

  - name: Sync Capacitor
    script: |
      npx cap sync ios

  - name: Install CocoaPods
    script: |
      cd ios/App
      pod install
    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - chavdahimanshu2010@gmail.com
